/*
 *  Copyright (c) 2010-2024 BSI Business Systems Integration AG
 *  Copyright (c) 2023-2024 Nils Israel
 *
 * This program is an extension of the original work from the Eclipse Scout Project,
 * available at https://www.eclipse.org/scout/.
 *
 *  This program and the accompanying materials are made
 *  available under the terms of the Eclipse Public License 2.0
 *  which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 *  SPDX-License-Identifier: EPL-2.0
 */
import {StaticLookupCall} from '@eclipse-scout/core';

export class AceModeLookupCall extends StaticLookupCall<string> {

  constructor() {
    super();
  }

  protected override _data(): any[] {
    return AceModeLookupCall.DATA;
  }

  static DATA = [
    ['abap', 'abap'],
    ['abc', 'abc'],
    ['actionscript', 'actionscript'],
    ['ada', 'ada'],
    ['alda', 'alda'],
    ['apache_conf', 'apache_conf'],
    ['apex', 'apex'],
    ['applescript', 'applescript'],
    ['aql', 'aql'],
    ['asciidoc', 'asciidoc'],
    ['asl', 'asl'],
    ['assembly_x86', 'assembly_x86'],
    ['astro', 'astro'],
    ['autohotkey', 'autohotkey'],
    ['batchfile', 'batchfile'],
    ['bibtex', 'bibtex'],
    ['c9search', 'c9search'],
    ['c_cpp', 'c_cpp'],
    ['cirru', 'cirru'],
    ['clojure', 'clojure'],
    ['cobol', 'cobol'],
    ['coffee', 'coffee'],
    ['coldfusion', 'coldfusion'],
    ['crystal', 'crystal'],
    ['csharp', 'csharp'],
    ['csound_document', 'csound_document'],
    ['csound_orchestra', 'csound_orchestra'],
    ['csound_score', 'csound_score'],
    ['csp', 'csp'],
    ['css', 'css'],
    ['curly', 'curly'],
    ['cuttlefish', 'cuttlefish'],
    ['d', 'd'],
    ['dart', 'dart'],
    ['diff', 'diff'],
    ['django', 'django'],
    ['dockerfile', 'dockerfile'],
    ['dot', 'dot'],
    ['drools', 'drools'],
    ['edifact', 'edifact'],
    ['eiffel', 'eiffel'],
    ['ejs', 'ejs'],
    ['elixir', 'elixir'],
    ['elm', 'elm'],
    ['erlang', 'erlang'],
    ['flix', 'flix'],
    ['forth', 'forth'],
    ['fortran', 'fortran'],
    ['fsharp', 'fsharp'],
    ['fsl', 'fsl'],
    ['ftl', 'ftl'],
    ['gcode', 'gcode'],
    ['gherkin', 'gherkin'],
    ['gitignore', 'gitignore'],
    ['glsl', 'glsl'],
    ['gobstones', 'gobstones'],
    ['golang', 'golang'],
    ['graphqlschema', 'graphqlschema'],
    ['groovy', 'groovy'],
    ['haml', 'haml'],
    ['handlebars', 'handlebars'],
    ['haskell', 'haskell'],
    ['haskell_cabal', 'haskell_cabal'],
    ['haxe', 'haxe'],
    ['hjson', 'hjson'],
    ['html', 'html'],
    ['html_elixir', 'html_elixir'],
    ['html_ruby', 'html_ruby'],
    ['ini', 'ini'],
    ['io', 'io'],
    ['ion', 'ion'],
    ['jack', 'jack'],
    ['jade', 'jade'],
    ['java', 'java'],
    ['javascript', 'javascript'],
    ['jexl', 'jexl'],
    ['json', 'json'],
    ['json5', 'json5'],
    ['jsoniq', 'jsoniq'],
    ['jsp', 'jsp'],
    ['jssm', 'jssm'],
    ['jsx', 'jsx'],
    ['julia', 'julia'],
    ['kotlin', 'kotlin'],
    ['latex', 'latex'],
    ['latte', 'latte'],
    ['less', 'less'],
    ['liquid', 'liquid'],
    ['lisp', 'lisp'],
    ['livescript', 'livescript'],
    ['logiql', 'logiql'],
    ['logtalk', 'logtalk'],
    ['lsl', 'lsl'],
    ['lua', 'lua'],
    ['luapage', 'luapage'],
    ['lucene', 'lucene'],
    ['makefile', 'makefile'],
    ['markdown', 'markdown'],
    ['mask', 'mask'],
    ['matlab', 'matlab'],
    ['maze', 'maze'],
    ['mediawiki', 'mediawiki'],
    ['mel', 'mel'],
    ['mips', 'mips'],
    ['mixal', 'mixal'],
    ['mushcode', 'mushcode'],
    ['mysql', 'mysql'],
    ['nasal', 'nasal'],
    ['nginx', 'nginx'],
    ['nim', 'nim'],
    ['nix', 'nix'],
    ['nsis', 'nsis'],
    ['nunjucks', 'nunjucks'],
    ['objectivec', 'objectivec'],
    ['ocaml', 'ocaml'],
    ['odin', 'odin'],
    ['partiql', 'partiql'],
    ['pascal', 'pascal'],
    ['perl', 'perl'],
    ['pgsql', 'pgsql'],
    ['php', 'php'],
    ['php_laravel_blade', 'php_laravel_blade'],
    ['pig', 'pig'],
    ['plain_text', 'plain_text'],
    ['plsql', 'plsql'],
    ['powershell', 'powershell'],
    ['praat', 'praat'],
    ['prisma', 'prisma'],
    ['prolog', 'prolog'],
    ['properties', 'properties'],
    ['protobuf', 'protobuf'],
    ['prql', 'prql'],
    ['puppet', 'puppet'],
    ['python', 'python'],
    ['qml', 'qml'],
    ['r', 'r'],
    ['raku', 'raku'],
    ['razor', 'razor'],
    ['rdoc', 'rdoc'],
    ['red', 'red'],
    ['redshift', 'redshift'],
    ['rhtml', 'rhtml'],
    ['robot', 'robot'],
    ['rst', 'rst'],
    ['ruby', 'ruby'],
    ['rust', 'rust'],
    ['sac', 'sac'],
    ['sass', 'sass'],
    ['scad', 'scad'],
    ['scala', 'scala'],
    ['scheme', 'scheme'],
    ['scrypt', 'scrypt'],
    ['scss', 'scss'],
    ['sh', 'sh'],
    ['sjs', 'sjs'],
    ['slim', 'slim'],
    ['smarty', 'smarty'],
    ['smithy', 'smithy'],
    ['snippets', 'snippets'],
    ['soy_template', 'soy_template'],
    ['space', 'space'],
    ['sparql', 'sparql'],
    ['sql', 'sql'],
    ['sqlserver', 'sqlserver'],
    ['stylus', 'stylus'],
    ['svg', 'svg'],
    ['swift', 'swift'],
    ['tcl', 'tcl'],
    ['terraform', 'terraform'],
    ['tex', 'tex'],
    ['text', 'text'],
    ['textile', 'textile'],
    ['toml', 'toml'],
    ['tsx', 'tsx'],
    ['turtle', 'turtle'],
    ['twig', 'twig'],
    ['typescript', 'typescript'],
    ['vala', 'vala'],
    ['vbscript', 'vbscript'],
    ['velocity', 'velocity'],
    ['verilog', 'verilog'],
    ['vhdl', 'vhdl'],
    ['visualforce', 'visualforce'],
    ['wollok', 'wollok'],
    ['xml', 'xml'],
    ['xquery', 'xquery'],
    ['yaml', 'yaml'],
    ['zeek', 'zeek']
  ];
}
