version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "nisrael"
    assignees:
      - "nisrael"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "nisrael"
    assignees:
      - "nisrael"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      eclipse-scout:
        patterns:
          - "org.eclipse.scout.rt:*"
        update-types:
          - "patch"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.codehaus.mojo:*"
          - "io.smallrye:*"
          - "com.mycila:*"
          - "org.sonatype.central:*"
        update-types:
          - "minor"
          - "patch"
      other-dependencies:
        exclude-patterns:
          - "org.eclipse.scout.rt:*"
          - "org.apache.maven.plugins:*"
          - "org.codehaus.mojo:*"
          - "io.smallrye:*"
          - "com.mycila:*"
          - "org.sonatype.central:*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "maven"

  # npm dependencies for ace module
  - package-ecosystem: "npm"
    directory: "/ace"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "nisrael"
    assignees:
      - "nisrael"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      eclipse-scout-npm:
        patterns:
          - "@eclipse-scout/*"
        update-types:
          - "patch"
      ace:
        patterns:
          - "ace-code"
        update-types:
          - "minor"
          - "patch"
      development:
        dependency-type: "development"
        exclude-patterns:
          - "@eclipse-scout/*"
          - "ace-code"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "npm"
      - "ace"

  # npm dependencies for codemirror module
  - package-ecosystem: "npm"
    directory: "/codemirror"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "nisrael"
    assignees:
      - "nisrael"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      eclipse-scout-npm:
        patterns:
          - "@eclipse-scout/*"
        update-types:
          - "patch"
      codemirror:
        patterns:
          - "@codemirror/*"
          - "thememirror"
          - "@ddietr/codemirror-themes"
        update-types:
          - "minor"
          - "patch"
      development:
        dependency-type: "development"
        exclude-patterns:
          - "@eclipse-scout/*"
          - "@codemirror/*"
          - "thememirror"
          - "@ddietr/codemirror-themes"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "npm"
      - "codemirror"

  # npm dependencies for demo module
  - package-ecosystem: "npm"
    directory: "/demo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "nisrael"
    assignees:
      - "nisrael"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      eclipse-scout-npm:
        patterns:
          - "@eclipse-scout/*"
        update-types:
          - "patch"
      codemirror:
        patterns:
          - "@codemirror/*"
          - "thememirror"
          - "@ddietr/codemirror-themes"
        update-types:
          - "minor"
          - "patch"
      ace:
        patterns:
          - "ace-code"
        update-types:
          - "minor"
          - "patch"
      development:
        dependency-type: "development"
        exclude-patterns:
          - "@eclipse-scout/*"
          - "@codemirror/*"
          - "thememirror"
          - "@ddietr/codemirror-themes"
          - "ace-code"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "npm"
      - "demo"
