= Additional form fields for Eclipse Scout
:toc: macro
:toc-title: Table of Contents
:toclevels: 4

The modules in this project provide wrapper modules for commonly used open source form field elements as extension to the [Eclipse Scout](https://eclipse.dev/scout/) framework.

toc::[]

== Versioning and Releases

The major and minor version of the modules in this repository match the major and minor version of the Eclipse Scout release they are intended to be used with. The patch version is incremented for every release of the addon modules. This means, that for example the sxda-scout-addon version 23.2.x should be compatible with all Eclipse Scout 23.2.y versions.

You should override the property `org.eclipse.scout.rt.version` in your root pom.xml to the version of the Eclipse Scout release you are using. For the npm modules, you should be fine because the dependency to the Eclipse Scout runtime is defined as a peer dependency.

Releases are published to https://central.sonatype.com/namespace/io.sxda.scout.addon[central.sonatype.com] and https://www.npmjs.com/package/@sxda/scout-addon-ace[npmjs.org]. The version number of the release is always the same for both repositories.

Snapshot versions are published to https://github.com/nisrael?tab=packages&repo_name=sxda-scout-addon[GitHub Packages] and https://www.npmjs.com/package/@sxda/scout-addon-ace[npmjs.org].

== Contributing

Contributions are welcome:

* If you found a bug, please open an issue or, if you are able to fix it, open a pull request.
* If you have an idea for a new form field element or an improvement of the existing one(s), please open an issue or even better a pull request.
* If you have a question, please open an issue.

== Elements

=== Ace Code Editor

The https://ace.c9.io[Ace Code Editor] is a web based code editor with syntax highlighting and code completion for many programming languages. The wrapper is implemented as  `AbstractAceField extends AbstractValueField<String>` and can be used in a form like any other value field.

==== Usage

To use the field in an Eclipse Scout Classic 23.2.y application, add the following modules to your application:

.your.app.client/pom.xml
[source,xml]
----
<!-- ... -->
<dependency>
  <groupId>io.sxda.scout.addon</groupId>
  <artifactId>ace.client</artifactId>
  <version>23.2.1</version>
</dependency>
<!-- ... -->
----

.your.app.ui.html/pom.xml
[source,xml]
----
<!-- ... -->
<dependency>
  <groupId>io.sxda.scout.addon</groupId>
  <artifactId>ace.ui.html</artifactId>
  <version>23.2.1</version>
</dependency>
<!-- ... -->
----

The node module `@sxda/scout-addon-ace` does not redistribute the transitive dependency `ace-builds`. This means that if there is a new version of the ace code editor, you can use that right away (assuming compatibility) and don't have to wait for a new release of the addon modules. The disadvantage is, that you have to add the ace code editor as a dependency yourself in addition to the `@sxda/scout-addon-ace` module.

Here are the dependencies you have to add to the `package.json` file of the ui.html module of your application :

.your.app.ui.html/packages.json
[source,json]
----
{
    "dependencies": {
      "@sxda/scout-addon-ace": "23.2.1",
      "ace-builds": "1.32.3"
  }
}
----

In the `index.ts` file of the ui.html module, the ace wrapper module needs to be imported:

.your.app.ui.html/src/main/js/index.ts
[source,typescript]
----
import * as sxda from '@sxda/scout-addon-ace';
Object.assign({}, sxda);
----

Finally, the ace code editor can be used in a form:

[source,java]
----
      @Order(1000)
      public class CodeField extends AbstractAceField {
        @Override
        protected int getConfiguredGridW() {
          return 2;
        }

        @Override
        protected String getConfiguredLabel() {
          return TEXTS.get("Code");
        }

        @Override
        protected String getConfiguredTheme() {
          return AceTheme.TWILIGHT.getConfigTerm();
        }

        @Override
        protected boolean getConfiguredShowPrintMargin() {
          return true;
        }

                @Override
        protected int getConfiguredTabSize() {
          return 2;
        }

        @Override
        protected boolean getConfiguredHighlightActiveLine() {
          return true;
        }

        @Override
        protected boolean getConfiguredUseSoftTabs() {
          return true;
        }

        @Override
        protected boolean getConfiguredUseWrapMode() {
          return false;
        }
      }
----

== License

This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0

Please also refer to the link:./NOTICE.md[NOTICE] file(s) that are distributed along with this source code.

To learn more about the Eclipse Public License 2.0, please refer to e.g. https://fossa.com/blog/open-source-software-licenses-101-eclipse-public-license/ or https://www.eclipse.org/legal/epl-2.0/faq.php.
