= Additional Form Fields for Eclipse Scout

This project provides wrapper modules for popular open-source web widgets as form field extensions for the https://eclipse.dev/scout/[Eclipse Scout] framework. The modules wrap browser-based widgets into Scout form fields, following Scout's client-server architecture and providing a familiar Scout API for Java developers.

== Available Modules

* **Ace Editor** - Wrapper for the https://ace.c9.io[Ace Code Editor]
* **CodeMirror** - Wrapper for https://codemirror.net/[CodeMirror 6]
* **Monaco Editor** - Wrapper for the https://microsoft.github.io/monaco-editor/[Monaco Editor] (VS Code editor)

The project is not limited to code editors and can be extended with wrappers for any open-source web widget (charts, rich text editors, data grids, calendars, etc.).

== Documentation

📚 **Full documentation is available at:** https://nisrael.github.io/sxda-scout-addon/

The documentation includes:

* Getting started guides for each module
* Installation instructions (Maven and npm)
* Usage examples and API documentation
* Developer guides for building from source and creating custom fields
* IntelliJ IDEA setup with live templates

== Quick Start

**Maven dependencies** (add to your `pom.xml`):
[source,xml]
----
<dependency>
  <groupId>io.sxda.scout.addon</groupId>
  <artifactId>ace.client</artifactId>
</dependency>
<dependency>
  <groupId>io.sxda.scout.addon</groupId>
  <artifactId>ace.ui.html</artifactId>
</dependency>
----

**npm package** (add to your `package.json`):
[source,bash]
----
npm install @sxda/scout-addon-ace
----

For complete installation and usage instructions, see the https://nisrael.github.io/sxda-scout-addon/[documentation].

== Versioning

This project's major.minor version matches Eclipse Scout's version. For example, version 25.2.x is compatible with Eclipse Scout 25.2.y.

Releases are published to https://central.sonatype.com/namespace/io.sxda.scout.addon[Maven Central] and https://www.npmjs.com/[npmjs.org].

== Building from Source

To build the project from source:

[source,bash]
----
mvn clean package
----

For detailed build instructions, requirements, and Maven configuration, see the https://nisrael.github.io/sxda-scout-addon/building-from-source.html[Building from Source] guide.

== Demo

Try the live demo: https://nisrael.github.io/sxda-scout-addon/

The demo showcases all available modules with various configurations.

== Contributing

Contributions are welcome:

* If you found a bug, please open an issue or, if you are able to fix it, open a pull request.
* If you have an idea for a new widget wrapper or an improvement of the existing one(s), please open an issue or even better a pull request.
* If you have a question, please open an issue.

== License

This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0

Please also refer to the link:./NOTICE.md[NOTICE] file(s) that are distributed along with this source code.

To learn more about the Eclipse Public License 2.0, please read e.g. https://fossa.com/blog/open-source-software-licenses-101-eclipse-public-license/ or https://www.eclipse.org/legal/epl-2.0/faq.php.
