# Additional form fields for Eclipse Scout

The modules in this repository are intended to provide wrapper modules for commonly used open source form field elements so that they can be used in an Eclipse Scout application.

## Versioning and Releases

The major and minor version of the modules in this repository match the major and minor version of the Eclipse Scout release they are intended to be used with. The patch version is incremented for every release of the addon modules. This means, that for example the sxda-scout-addon version 23.2.x should be compatible with all Eclipse Scout 23.2.y versions.

You should override the property `org.eclipse.scout.rt.version` in your root pom.xml to the version of the Eclipse Scout release you are using. For the npm modules, you should be fine because the dependency to the Eclipse Scout runtime is defined as a peer dependency.

Releases are published to https://central.sonatype.com/namespace/io.sxda.scout.addon[central.sonatype.com] and https://www.npmjs.com/package/@sxda/scout-addon-ace[npmjs.org]. The version number of the release is always the same for both repositories.

Snapshot versions are (if at all) published to GitHub Packages only.

## Elements

### Ace Code Editor

The https://ace.c9.io[Ace Code Editor] is a web based code editor with syntax highlighting and
code completion for many programming languages. The wrapper is implemented as  `AbstractAceField extends AbstractValueField<String>` and can be used in a form like any other value field.

To use the field in an Eclipse Scout Classic application, add the following modules to your application:

.your.app.client/pom.xml
[source,xml]
----
<!-- ... -->
<dependency>
  <groupId>io.sxda.scout.addon</groupId>
  <artifactId>ace.client</artifactId>
  <version>23.2.1</version>
</dependency>
<!-- ... -->
----

.your.app.ui.html/pom.xml
[source,xml]
----
<!-- ... -->
<dependency>
  <groupId>io.sxda.scout.addon</groupId>
  <artifactId>ace.ui.html</artifactId>
  <version>23.2.1</version>
</dependency>
<!-- ... -->
----

The node module `@sxda/scout-addon-ace` does not redistribute the transitive dependency `ace-builds`, so both modules need to be added to the `package.json` file of the ui.html module:

.your.app.ui.html/packages.json
[source,json]
----
{
    "dependencies": {
      "@sxda/scout-addon-ace": "23.2.1",
      "ace-builds": "1.32.3"
  }
}
----

In the `index.ts` file of the ui.html module, the ace wrapper module needs to be imported:

.your.app.ui.html/src/main/js/index.ts
[source,typescript]
----
import * as sxda from '@sxda/scout-addon-ace';
Object.assign({}, sxda);
----

Finally, the ace code editor can be used in a form:

[source,java]
----
      @Order(1000)
      public class CodeField extends AbstractAceField {
        @Override
        protected int getConfiguredGridW() {
          return 2;
        }

        @Override
        protected String getConfiguredLabel() {
          return TEXTS.get("Code");
        }

        @Override
        protected String getConfiguredTheme() {
          return AceTheme.TWILIGHT.getConfigTerm();
        }

        @Override
        protected boolean getConfiguredShowPrintMargin() {
          return true;
        }

                @Override
        protected int getConfiguredTabSize() {
          return 2;
        }

        @Override
        protected boolean getConfiguredHighlightActiveLine() {
          return true;
        }

        @Override
        protected boolean getConfiguredUseSoftTabs() {
          return true;
        }

        @Override
        protected boolean getConfiguredUseWrapMode() {
          return false;
        }
      }
----

## IntelliJ IDEA templates

.IntelliJ IDEA templates
[source,xml]
----
<template name="scoutprop" value="  @Override&#10;  @ConfigProperty(ConfigProperty.$TYPE$)&#10;  public void set$Prop$($Type$ $prop$) {&#10;    propertySupport.setProperty$Type$(PROP_$PROP$, $prop$);&#10;  }&#10;&#10;  @Override&#10;  @ConfigProperty(ConfigProperty.$TYPE$)&#10;  public $Type$ get$Prop$() {&#10;    return propertySupport.getProperty$Type$(PROP_$PROP$);&#10;  }&#10;&#10;  @ConfigProperty(ConfigProperty.$TYPE$)&#10;  protected $Type$ getConfigured$Prop$() {&#10;    return $default$;&#10;  }" toReformat="false" toShortenFQNames="true">
  <variable name="TYPE" expression="" defaultValue="STRING" alwaysStopAt="true" />
  <variable name="Prop" expression="" defaultValue="Name" alwaysStopAt="true" />
  <variable name="Type" expression="" defaultValue="String" alwaysStopAt="true" />
  <variable name="prop" expression="" defaultValue="name" alwaysStopAt="true" />
  <variable name="PROP" expression="" defaultValue="NAME" alwaysStopAt="true" />
  <variable name="default" expression="" defaultValue="&quot;default&quot;" alwaysStopAt="true" />
  <context>
    <option name="JAVA_CODE" value="true" />
  </context>
</template>

<template name="scoutprop" value="set$Varname$($varname$: $type$) {&#10;    this.setProperty('$varname$', $varname$);&#10;  }&#10;&#10;  _set$Varname$($varname$: $type$){&#10;    this.$varname$ = $varname$;&#10;  }&#10;&#10;  get$Varname$(): $type${&#10;    return this.$varname$;&#10;  }&#10;&#10;  _render$Varname$(){&#10;    this.editor.session.set$Varname$(this.$varname$);&#10;  }" toReformat="false" toShortenFQNames="true">
  <variable name="Varname" expression="capitalize($varname$)" defaultValue="" alwaysStopAt="true" />
  <variable name="varname" expression="" defaultValue="" alwaysStopAt="true" />
  <variable name="type" expression="" defaultValue="" alwaysStopAt="true" />
  <context>
    <option name="JAVA_SCRIPT" value="true" />
    <option name="TS_CLASS" value="false" />
    <option name="TS_EXPRESSION" value="false" />
    <option name="TS_STATEMENT" value="false" />
    <option name="TypeScript" value="true" />
  </context>
</template>
----

This program and the accompanying materials are made
available under the terms of the Eclipse Public License 2.0
which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0
